language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

# Disable branch whitelist until migration to QGIS3 is completed
#branches:
#  only:
#    - master

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo apt-get install -y git pylint pep8 python-nose python-coverage pyflakes python-nosexcover python-qt4
  - pip install nose-exclude

before_script:
  - echo "Build starting on " `date`
  - export PYTHONPATH=`pwd`

script:
  - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=.
  - make pep8

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - ismail@kartoza.com